下载Unity插件:
  active: true
  count: 0
下载几本书籍:
  active: true
  count: 0
丢一会沙包:
  active: true
  count: 0
书法:
  active: true
  count: 0
伸展吐纳一下:
  active: true
  count: 0
做一个手工，比如折纸、叠道具、纸飞机之类的:
  active: true
  count: 0
做几个俯卧撑:
  active: true
  count: 1
做几个倒立:
  active: true
  count: 0
做几个平板支撑:
  active: true
  count: 0
像高手一样踢一会毽子:
  active: true
  count: 0
写点散文:
  active: true
  count: 0
写点日记，记录心情:
  active: true
  count: 0
写首小诗:
  active: true
  count: 0
创作几个镜头:
  active: false
  count: 0
创作博馆平台，走上人生巅峰:
  active: true
  count: 0
创作点东西:
  active: true
  count: 0
制作全平台打卡软件:
  active: true
  count: 0
午睡:
  active: true
  count: 0
叠一只纸心:
  active: true
  count: 0
叠一只纸青蛙:
  active: true
  count: 0
叠一只纸风车:
  active: true
  count: 0
叠一只纸飞机:
  active: true
  count: 0
叠一只纸鹤:
  active: true
  count: 0
只刷半道算法题:
  active: true
  count: 0
吃个桃子:
  active: true
  count: 0
吃个火龙果:
  active: true
  count: 0
吃个猕猴桃:
  active: true
  count: 0
吃几个橘子:
  active: true
  count: 0
吃几个草莓:
  active: true
  count: 0
吃块冰糕:
  active: true
  count: 1
吃块巧克力:
  active: true
  count: 0
吃块甘蔗:
  active: false
  count: 0
吃块菠萝:
  active: true
  count: 0
吃块西瓜:
  active: true
  count: 0
吃根火腿:
  active: true
  count: 0
吃根辣条:
  active: true
  count: 0
吃根香蕉:
  active: true
  count: 0
吃点樱桃:
  active: true
  count: 0
吃点葡萄:
  active: true
  count: 0
听一听古筝:
  active: true
  count: 0
听一听名曲:
  active: true
  count: 0
听一听老友记:
  active: true
  count: 0
听一段相声:
  active: true
  count: 1
品杯咖啡:
  active: true
  count: 0
喝两口水:
  active: true
  count: 0
喝包牛奶:
  active: true
  count: 0
喝包酸奶:
  active: true
  count: 0
喝瓶冰红茶:
  active: true
  count: 0
喝瓶可乐:
  active: true
  count: 0
喷洒一会水壶:
  active: true
  count: 0
大字躺:
  active: true
  count: 1
大脑放空:
  active: true
  count: 0
学一丁点思修:
  active: true
  count: 0
学一丁点概率:
  active: true
  count: 0
学一丁点毛概:
  active: true
  count: 0
学一丁点算法:
  active: true
  count: 1
学一丁点系统:
  active: true
  count: 0
学一丁点线代:
  active: true
  count: 0
学一丁点网络:
  active: true
  count: 0
学一丁点计组:
  active: true
  count: 0
学一丁点马哲:
  active: true
  count: 0
学一丁点高数:
  active: true
  count: 0
学一句长难句:
  active: true
  count: 1
学一学政治军事:
  active: true
  count: 0
学一学时尚设计:
  active: true
  count: 0
学一学自然科学，比如生物，物理等:
  active: true
  count: 0
学一学葫芦丝:
  active: true
  count: 0
学一学财富经济:
  active: true
  count: 0
学一张折纸:
  active: true
  count: 0
学习一个成语典故:
  active: true
  count: 0
学习渲染技巧:
  active: false
  count: 0
学学漫画:
  active: true
  count: 0
学点世界语:
  active: true
  count: 0
学点俄语:
  active: true
  count: 0
学点日语:
  active: true
  count: 0
学点法语:
  active: true
  count: 0
学点英语:
  active: true
  count: 1
完善下采访视频:
  active: true
  count: 0
建模一个物品:
  active: false
  count: 0
念一段可爱的咒语:
  active: true
  count: 0
念一段抽风的咒语:
  active: true
  count: 0
念一段炫酷的咒语:
  active: true
  count: 0
念一段神秘的咒语:
  active: true
  count: 0
找找好玩的材质:
  active: false
  count: 0
找找好玩的贴图:
  active: false
  count: 0
投掷一会卡片:
  active: true
  count: 0
挑一张喜欢的图案进行涂色:
  active: true
  count: 0
挑一本经典名著读:
  active: true
  count: 0
挑一篇诗经:
  active: true
  count: 0
挑战一分钟手绘:
  active: true
  count: 0
掐一个传递信息的手决:
  active: true
  count: 0
掐一个金碧辉煌的手决:
  active: true
  count: 0
掐一个隐秘的手决:
  active: true
  count: 0
摆一个不开心的姿势:
  active: true
  count: 0
摆一个低调的姿势:
  active: true
  count: 0
摆一个可爱的姿势:
  active: true
  count: 0
摆一个炫酷的姿势:
  active: true
  count: 0
摆一摆积木:
  active: true
  count: 0
散散步:
  active: true
  count: 1
早睡:
  active: true
  count: 0
早起:
  active: true
  count: 0
炫酷的投掷一会飞镖:
  active: true
  count: 1
猜一个灯谜:
  active: true
  count: 0
猜一个脑筋急转弯:
  active: true
  count: 0
猜一个谜语:
  active: true
  count: 0
玩一会抛石子游戏:
  active: true
  count: 0
玩弹弓:
  active: true
  count: 0
玩硬币:
  active: true
  count: 0
用随机100个汉字组成词语:
  active: true
  count: 0
画一个好看的符号:
  active: true
  count: 0
画一个帮派的标志符号:
  active: true
  count: 0
画一个有趣的符号:
  active: true
  count: 0
画一个神秘的符号:
  active: true
  count: 0
画几帧炫酷的动画:
  active: true
  count: 0
看点技术书籍:
  active: true
  count: 0
石头剪刀布:
  active: true
  count: 0
练一练钢琴:
  active: true
  count: 0
给百度网盘归档分类:
  active: true
  count: 0
编一段相声:
  active: true
  count: 0
编一段简谱:
  active: true
  count: 0
翻花绳:
  active: true
  count: 0
背一背写作:
  active: true
  count: 0
背几个单词:
  active: true
  count: 0
蒙头缩成球:
  active: true
  count: 0
装作神秘高手投掷几枚飞镖:
  active: true
  count: 0
见识见识名画:
  active: true
  count: 0
记录小说片段或设想:
  active: true
  count: 0
设计个小动画:
  active: true
  count: 0
设计几个动作:
  active: false
  count: 0
试试手绘:
  active: true
  count: 0
试试板绘:
  active: true
  count: 0
读一篇散文:
  active: true
  count: 0
读一读世界史:
  active: true
  count: 0
读一读人类简史:
  active: true
  count: 2
读一读英文诗:
  active: true
  count: 0
读一读论语:
  active: true
  count: 0
读一读资本论:
  active: true
  count: 2
读一读顾城诗集:
  active: true
  count: 0
读几篇阅读:
  active: true
  count: 0
赏一首诗词歌赋:
  active: true
  count: 0
赏析一副名画:
  active: true
  count: 0
跑跑步:
  active: true
  count: 2
释放一个OW技能:
  active: true
  count: 0
释放一个火影技能:
  active: true
  count: 0
闭眼小憩:
  active: true
  count: 0
随心所欲的打滚:
  active: true
  count: 1
随心所欲的涂鸦随机到的汉字:
  active: true
  count: 0
