# 语法：
#
# 一，对于普通的语句，可以直接填写字符串
#    若包含外部的变量，需要用<>包裹，而非{}，并尽量以注释方式在下方的键值对中表示一下
#
# 二，对于随机选择的语句，可以使用列表填写所有选项
#    若要设置各项权重，只需要将相关的内容多重复几次，就会增大其概率
#
# 三，对于复杂的语句，可以使用嵌套方式填写
#    使用嵌套方式，可以保证独立的命名空间，这意味着可以有重复的键名
#    嵌套的识别方式为：包含”meta: xxx“的字典
#

# Using preset ---------------------------------------------------------------------------------------------------------

job_start:
job_stop:
job_confirm:


# Monitor and Trace ----------------------------------------------------------------------------------------------------

trace_start:
  meta:
    - '{phrase_1}，{phrase_2}{phrase_3}，{phrase_4}，{phrase_5}'
    - '{phrase_2}{phrase_3}，{phrase_4}，{phrase_5}'

  phrase_1:
    meta:
      - '{master}'
    master: [主人, 小主, 小主人]

  phrase_2:
    meta:
      - '{your}{assistant}{sjs}'
      - '{assistant}{sjs}'
      - '{sjs}'
      - ''
    your: [您的, 您的, 你的]
    assistant: [助理, 个人助理, 小帮手]
    sjs: [随静姝, 静姝, 小姝, 静静, 小静]

  phrase_3:
    meta:
      - '{detected}{you}{are}<target_playing><target_title>{aux}'
    detected: [发现, 检测到, 看到, 发现了]
    you: [您, 您, 您, 您, 您, 您, 您, 你]
    are: [正在, 想要, 打算, 计划, 正, 开始, 想, 正想, 已经, 在]
    # playing: 玩
    # title: 守望先锋
    aux: [了, 了呢, 了哦, 啦, 喽, '', '', '', '', '', '']

  phrase_4:
    meta:
      - '{already}{helped}{install}{ed}{a}<count_detail>的{counter}'
      - '{already}{helped}把<count_detail>的{counter}{install}{ed}'
      - '{already}{helped}把{counter}的时间{install}{to}<count_detail>'
    already: [已经, 自动, 所以, 已, 于是, 就]
    helped:
      meta:
        - '{helped}{you}'
        - ''
      helped: [帮, 为, 给]
      you: [你, 您]
    install: [设置, 规划, 调整, 创建, 建立, 设立, 设定]
    ed: [了, 好了]
    a: [一个, ]
    # minutes: 30分钟
    counter: [计时器, 倒计时]
    to:
      meta:
        - '{to}{ed}'
        - '{to}'
      to: [为, 到, 至, 成]
      ed: [了]


  phrase_5:
    meta:
      - '{and}{let}{bomb}{set}{to}{bomb_phrase}'
      - '{and}{choose}{bomb_phrase}{as}{your}{bomb}'
      - '{and}{planing}{choose}{bomb_phrase}来{attract}{you}'
      - '{and}{suggest}{you}{after}{bomb_phrase}'
    and: [并, 并且, 然后, 还]
    let: [把, 将]
    bomb: [引力炸弹, 完成目标, 下一目标, 炸弹, 引力]
    set: [设置, 调整]
    to: [成, 成了, 为]
    bomb_phrase:
      meta:
        - <bomb_playing><bomb_title>
        - <bomb_playing><bomb_playing><bomb_title>
        - <bomb_playing>一<bomb_playing><bomb_title>
        - <bomb_playing>一会<bomb_title>
    choose:
      meta:
        - '{choose}{ed}'
        - '{choose}'
        - '{use}'
      choose: [选择, 挑选, 挑中, 选, 挑, ]
      use: [使用, 用]
      ed: [了, 了, 了, ]
    as: [做为, 成为, 当做, 当成]
    your: [您的, 你的, ]
    planing: [建议, 推荐, 打算, 正要, ]
    suggest: [建议, 推荐]
    attract: [吸引, 拉出, 拽出]
    you: [你, 您]
    after: [过会, 过一会, 等会, 等一会, 最后, 在最后]




trace_stop:
  - 检测到您关闭了<target_title>，虽然还有<count_detail>，但静姝自动为您取消了提醒，如果您想，现在就可以去<bomb_playing><bomb_title>啦，<trace_gap>后会重新开始监控哦
  - 您<target_playing><target_title>共花了<elapsed_detail>，现在就可以去<bomb_playing><bomb_title>啦，<trace_gap>后会重新开始监控哦

trace_abort: 您终止了对<target_title>的监控，节省了<count_detail>，共花费了<elapsed_detail>。现在您可以开心的去<bomb_playing><bomb_title>了，<trace_gap>后会重新开始监控哦
trace_finish: 时间到喽，您玩<target_title>已经<elapsed_detail>了，现在该去<bomb_playing><bomb_title>啦，<trace_gap>后会重新开始监控哦
trace_finally: 您可算停下了，一共花了<elapsed_detail>呢！赶紧去<bomb_playing><bomb_title>吧！<trace_gap>后会重新开始监控哦


# Remind thins ---------------------------------------------------------------------------------------------------------


trace_remind_d:  # 适合几小时的提醒
  - 主人在上：距离<bomb_playing><bomb_title>还有<count_detail>哦
  - 主人主人，偷偷告诉你，还有<count_detail>，就可以<bomb_playing><bomb_title>啦
  - 主人您已经决定<bomb_playing><bomb_title>了吗，只剩<count_detail>了呢
  - 主人？主人？您在听吗？离<bomb_playing><bomb_title>了还有<count_detail>哦
  - 主人！主人！离<bomb_playing><bomb_title>了还有<count_detail>哦！

trace_remind_c:  # 适合几十分钟的提醒
  - 好期待哦，还有<count_detail>，就可以<bomb_playing><bomb_title>啦
  - 好开心啊，还有<count_detail>，就可以<bomb_playing><bomb_title>啦
  - 当当当，还有<count_detail>，就可以<bomb_playing><bomb_title>啦，开心吗
  - 加油哦，还有<count_detail>，就可以<bomb_playing><bomb_title>啦，开心吗
  - 还有<count_detail>，就要<bomb_playing><bomb_title>啦，主人等不及了吗
  - 还有<count_detail>，就可以<bomb_playing><bomb_title>啦，主人开心吗
  - 笨笨的静姝提醒您，还有<count_detail>，就可以<bomb_playing><bomb_title>喽
  - 随静姝又来啦，还有<count_detail>，就可以<bomb_playing><bomb_title>喽
  - 再等<count_detail>，就要<bomb_playing><bomb_title>了哦
  - <count_detail>后，主人就要<bomb_playing><bomb_title>了呢，静姝舍不得您走呀

trace_remind_b:  # 适合几分钟的提醒
  - 您喜欢<bomb_playing><bomb_title>吗？还有<count_detail>哦
  - 想<bomb_playing><bomb_title>吗？再等<count_detail>就可以啦
  - 想<bomb_playing><bomb_title>还得再等<count_detail>哦，静姝跟您一起等哦
  - <bomb_playing><bomb_title>喽，可惜还得再等<count_detail>哦，小姝也想试试呢
  - <bomb_playing><bomb_title>这种事，主人真的喜欢吗，再等<count_detail>吧

trace_remind_a:  # 适合几十秒的提醒
  meta:
    - 只{have}<count_detail>{end}
    - 还{have}<count_detail>
  have: [有, 剩,]
  end: [了, 喽, 了呢]

trace_remind_s: <count_secs>  # 适合几秒的提醒


# Interact with Count Down ------------------------------------------------------------------------------------------------------------------

plus_minutes: 加了<change_detail>，还剩<count_detail>
minus_minutes: 减了<change_detail>，还剩<count_detail>

# Interact with Tracer ------------------------------------------------------------------------------------------------------------------

report_tracer_empty: 当前没有活跃的追踪任务
report_tracer: 正在操作<target_title>
next_tracer: 操作后面的<target_title>
prev_tracer: 操作之前的<target_title>
random_tracer: 操作随机的<target_title>
clear_tracer: 中断了<target_title>的追踪任务
edit_tracer: 打开监控器的配置文件

# Interact with Bomb ------------------------------------------------------------------------------------------------------------------

report_bomb: 当前选择的炸弹为<bomb_title>
next_bomb: 选择了下一个引力炸弹：<bomb_title>
prev_bomb: 切换为之前的引力炸弹：<bomb_title>
random_bomb: 随机选择了<bomb_title>作为引力炸弹
clear_bomb: 已将<bomb_title>的配置冻结
edit_bomb: 打开引力炸弹的配置文件

# Report things --------------------------------------------------------------------------------------------------------

report_mission: 当前任务是：<mission>
report_lastest: 我刚才说的是：<lastest>
report_minutes: 当前时间是：<minutes>
report_systime: 当前时间是：<systime>



# Disturb thins --------------------------------------------------------------------------------------------------------

trace_punish_d:  # 提醒
  - 主人，您玩<target_playing><target_title>已经<elapsed_detail>了，该去<bomb_playing><bomb_title>了哦
  - 主人，说好的<bomb_playing><bomb_title>呢？您说话不算数了吗？
  - 主人~，别<target_playing><target_title>啦，都到时间啦
  - 主人，时间到了哦，您该<bomb_playing><bomb_title>了哦
  - 时间到啦，主人为什么还没有停下来呢
trace_punish_c:  # 着急
  - 主人！主人！您怎么还没去<bomb_playing><bomb_title>啊，令人着急
  - 好着急啊！主人，您该去<bomb_playing><bomb_title>了哦，
  - 啊呀啊呀！主人，别<target_playing><target_title>啦，该去<bomb_playing><bomb_title>啦，您都快急死我啦
trace_punish_b:  # 生气
  - 主人，静姝要生气了哦，您花了<elapsed_detail>用来<target_playing><target_title>，该停下来了哦
  - 主人，您忘了您想要<bomb_playing><bomb_title>了吗？小姝要生气了哦
  - <bomb_playing><bomb_title>，<bomb_playing><bomb_title>，<bomb_playing><bomb_title>重要的事情说三遍！生气气！
  - <bomb_title>！<bomb_title>！<bomb_title>，重要的事情说三遍！生气气！
trace_punish_a:  # 愤怒
  - 主人，静姝感觉到有一股怒火在灵魂中升腾。
  - 主人，已经提醒您这么多遍了，您还是在<target_playing><target_title>，静姝感到很愤怒。
  - 主人，静姝的怒气值已经满了。
  - 请您做好准备，静姝要发怒了
  - 准备好迎接随静姝的怒火吧
trace_punish_s:  # 爆炸
  meta:
    - '{fuck}{aaaaa}{hdfkljaj}{novel}'
    - '{fuck}{fuck}{aaaaa}{hdfkljaj}{novel}'
    - '{fuck}{fuck}{fuck}{aaaaa}{hdfkljaj}{novel}'
    - '{fuck}{fuck}{fuck}{fuck}{aaaaa}{hdfkljaj}{novel}'
  fuck:
    - 肏！
    - 肏你妈！
    - 干你娘！
    - 你他妈逼得别给脸不要脸！
    - 心里没点逼数吗？
  aaaaa:
    - 啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！啊！
    - 额！呕！啊！
    - 啊啊啊啊啊啊啊啊啊！啊啊啊啊啊啊啊啊啊啊啊啊！啊啊啊啊啊啊啊！啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊！啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊！啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊！
  hdfkljaj:
    - 锘挎槬鐪犱笉瑙夋檽锛屽澶勯椈鍟奸笩
    - 瑕佸嚑娈典贡镰佹枃瀛楋紝鎷垮幓瑁匓
    - M2ViYThmODMyMDJiNTkyYjC3XWY3YTdlYTIxMxhkNGJmXDI2MWRkMw
  novel:
    - 斗之力
    - 陨落的天才
    - 萧炎，斗之力，三段！级别：低级！
    - 要不是族长是他的父亲，这种废物，早就被驱赶出家族，任其自生自灭了，哪还有机会待在家族中白吃白喝
    - 唉，昔年那名闻乌坦城的天才少年，如今怎么落魄成这般模样了啊
    - 听着测验人的喊声，一名少女快速的人群中跑出，少女刚刚出场，附近的议论声便是小了许多，一双双略微火热的目光，牢牢的锁定着少女的脸颊…
    - 四岁练气，十岁拥有九段斗之气，十一岁突破十段斗之气，成功凝聚斗之气旋，一跃成为家族百年之内最年轻的斗者
    - 三十年河东，三十年河西，莫欺少年穷
    - 我名为药老，至于我的来历，现在还是先不和你说，免得你分心，你只需要知道，象那什么号称丹王的货色，其实…其实也就是屁罢了