# 语法：
#
# 一，对于内部锚点，建议使用'【】'符号包裹起来，避免被找到
#
# 二，对于全局变量，需要使用'<>'符号包裹起来，才会被识别
#    全局变量需要使用独特的前缀区分，避免在语句中引用时，和其他表达的全局变量重名


# ------------------------------------------------------------------------------------------------------------------

【公共选项】: &default
  active: True
  frequency: '10s'
  count_short: '25m'
  trace_gap: '25s'
  start_lag: '20s'

【公共游戏】: &game
  <target_playing>: ['打', '玩']
  <<: *default
【公共网页】: &website
  <target_playing>: ['打开', '玩', '刷', '逛', '浏览']
  <<: *default

# ------------------------------------------------------------------------------------------------------------------

守望先锋:
  <target_title>: ['守望先锋', '守望先锋', '守望先锋', '守望', '游戏']
  <<: *game
逆水寒:
  <target_title>: ['逆水寒', '逆水寒', '逆水寒', '逆水寒', '逆水寒', '网易的逆水寒', '逆水寒网游', '网游逆水寒']
  <<: *game
知乎:
  <target_title>: ['知乎', '知乎', '知乎', '知乎', '知乎', '知乎', '逼乎', '问答社区', '破乎', '小破乎', '贵乎']
  <<: *website
哔哩哔哩:
  <target_title>: ['B站', 'B站', 'B站', 'B站', 'B站', '哔哩哔哩', '小破站', 'bilibili' ]
  <<: *website