# 语法：
#
# 一，对于内部锚点，建议使用【】符号包裹起来，避免被找到
#
# 二，对于全局变量，需要使用<>符号包裹起来，才会被识别
#    全局变量需要使用独特的前缀区分，避免在语句中引用时，和其他表达的全局变量重名
#
# 三：若冻结某任务时，该任务正在活跃中，则要等到活跃任务完成后才会成功冻结
#
# 四：监控间隔，必须小于追踪间隔。
#    否则才隔五秒就重新开始监控，但这时还没有刷新监控列表，那么就会执行惩罚

# ------------------------------------------------------------------------------------------------------------------

【公共选项】: &default
  active: true
  count: 0

  frequency: 1s
  count_short: 21m

  trace_gap: 30s
  punish_gap: 30s
  start_lag: 10s
  stop_lag: 10s

【公共游戏】: &game
  <target_playing>: [打, 玩]
  <<: *default
【公共网页】: &website
  <target_playing>: [打开, 玩, 刷, 逛, 浏览]
  <<: *default
【公共小说】: &novel
  <target_playing>: [读, 看, 阅读, 浏览]
  <<: *default

# ------------------------------------------------------------------------------------------------------------------

守望先锋:
  <target_title>: [守望先锋, 守望先锋, 守望先锋, 守望, 守望游戏]
  <<: *game
  count: 71
逆水寒:
  <target_title>: [逆水寒, 逆水寒, 逆水寒, 逆水寒, 逆水寒, 网易的逆水寒, 逆水寒网游, 网游逆水寒]
  <<: *game
  count: 2
ARK:
  <target_title>: [方舟, 方舟：进化生存]
  <<: *game
  count: 18

知乎:
  <target_title>: [知乎, 知乎, 知乎, 知乎, 知乎, 知乎, 逼乎, 问答社区, 破乎, 小破乎, 贵乎]
  <<: *website
  count: 16
哔哩哔哩:
  <target_title>: [B站, B站, B站, B站, B站, 哔哩哔哩, 小破站, bilibili]
  <<: *website
  count: 15

小说:
  <target_title>: [小说, 闲书, 杂书]
  <<: *novel
  count: 12
  count_short: 4h
